### ISSUE TITLE
Версия 2 - Статьи

### ISSUE THREAD

**Issue by vsezbs** [moseffect21/okolokalyana_front#4]
дизайн - https://www.figma.com/design/Fpkc72d0b1lPcrIhWgwFc0/%D0%9E%D0%BA%D0%BE%D0%BB%D0%BE-%D0%9A%D0%B0%D0%BB%D1%8C%D1%8F%D0%BD%D0%B0-2?node-id=862-543&t=notv5TdtuSTUPtOw-0

### Список статей
- [x] Выполнено

#### Должна содержать:
Хлебные крошки 
Заголовок
Фильтры по:
- типу статьи
- тематике 

Сортировка по:
- рейтинг
- обновление
- линейкам

Ну и сам список статей, у каждой из которых:
- Фото 
- название
- дата создания

### Страница статьи
- [x] Выполнено
#### Должна содержать:
Хлебные крошки
кнопка назад к списку
Название статьи в заголовке
контент статьи
счетчики комментов и лайков
комментарии к статье

**Comment by moseffect21** [comment]
**Список статей**
Фильтры по тематике - это по сути "категории" статей, у которых указан `parent`
Сортировка по линейкам - хз как это сделать, бэк не умеет, да и в базе нет данных. Так что это скипаем, полагаю
