### ISSUE TITLE
Версия 2 - Прокурочный цех

### ISSUE THREAD

**Issue by vsezbs** [moseffect21/okolokalyana_front#5]
Дизайн - https://www.figma.com/design/Fpkc72d0b1lPcrIhWgwFc0/%D0%9E%D0%BA%D0%BE%D0%BB%D0%BE-%D0%9A%D0%B0%D0%BB%D1%8C%D1%8F%D0%BD%D0%B0-2?node-id=714-919&t=notv5TdtuSTUPtOw-0

### Страница "поиска"
- [ ] Выполнено

#### Должна содержать:
Хлебные крошки
Заголовок
Фильтры:
- Чаша
- Табак
- Калауд
- Субьективная оценка
- Обьективная оценка
- Прокурщик

Остальной контент ещё обсудим

### Продолжение предыдущей страницы - "результаты поиска"
- [x] Выполнено

#### Должна содержать:
Хлебные крошки
Заголовок
Фильтры:
- Чаша
- Табак
- Калауд
- Субьективная оценка
- Обьективная оценка
- Прокурщик

Список подходящик под критерии "прокуров"

### Продолжение предыдущей страницы - модалка "Прокура"
- [x] Выполнено

#### Должна содержать:
Заголовок
Кнопка закрыть
контент "прокура"

**Comment by moseffect21** [comment]
Пора обсуждать че выводим на странице поиска, ну и чем она отличается от результатов поиска)))
