### ISSUE TITLE
Версия 2 - Шоурум

### ISSUE THREAD

**Issue by vsezbs** [moseffect21/okolokalyana_front#6]
дизайн - https://www.figma.com/design/Fpkc72d0b1lPcrIhWgwFc0/%D0%9E%D0%BA%D0%BE%D0%BB%D0%BE-%D0%9A%D0%B0%D0%BB%D1%8C%D1%8F%D0%BD%D0%B0-2?node-id=714-919&t=notv5TdtuSTUPtOw-0

### Список позиций в шоуруме
- [x] Выполнено

#### Должна содержать:
Хлебные крошки
Заголовок 
Вывести данные из АПИ:
https://github.com/moseffect21/okolo_kalyana/issues/17

**Comment by moseffect21** [comment]
В мобилке немного изменил галлерею.
Сделал мини картинки снизу, так удобнее на мобилке
